[Base]
; Nord color palette
main_fg                               = 81A1C1 ; The color of the completed portion of
                                               ; the music progress bar, play button
                                               ; heart button, song name, the left
                                               ; side bar buttons' text strings when
                                               ; they are selected, and the song text
                                               ; strings
secondary_fg                          = ECEFF4 ; The color of the left side bar
                                               ; buttons' text strings when they are
                                               ; not selected
main_bg                               = 3B4252 ; The background color of the left
                                               ; side bar and the bottom bar
sidebar_and_player_bg                 = 434C5E ; The background color of the area
                                               ; where you browse songs
cover_overlay_and_shadow              = 81A1C1
indicator_fg_and_button_bg            = ECEFF4 ; The horizontal highlight underneath
                                               ; the current selected tab in the
                                               ; browse page
pressing_fg                           = FF0000
slider_bg                             = D8DEE9 ; The color of the remaining portion of
                                               ; the music progress bar
sidebar_indicator_and_hover_button_bg = 2E3440 ; The background gradient on the
                                               ; selected tab on the left side bar
scrollbar_fg_and_selected_row_bg      = 3B4252 ; The gradient vertical accent on the
                                               ; left side bar
pressing_button_fg                    = FF0000
pressing_button_bg                    = FF0000
selected_button                       = FF0000
miscellaneous_bg                      = 3B4252 ; Background color of "Added to/
                                               ; removed from favorite songs"
                                               ; dialog
miscellaneous_hover_bg                = FF0000
preserve_1                            = FFFFFF
