colored_output = "true"
complete_from_path = "true"
completion_mode = "circular"
edit_mode = "vi"
pager = "bat"
path = [
    "/Library/Java",
    "/Users/abelsen/.nix-profile/bin",
    "/Users/abelsen/.local/bin",
    "/Users/abelsen/.rbenv/shims",
    "/usr/local/smlnj/bin",
    "/usr/local/lib/ruby/gems/3.0.0/bin",
    "/Users/abelsen/bin",
    "/usr/local/bin",
    "/usr/local/opt/ruby/bin",
    "/Users/abelsen/.cargo/bin",
    "/usr/local/opt/llvm@9/bin",
    "/usr/bin",
    "/bin",
    "/usr/sbin",
    "/sbin",
    "/Library/TeX/texbin",
    "/opt/X11/bin",
]
prompt = "echo $(starship prompt)"
rm_always_trash = "true"
startup = ["alias rm = trash"]

[env]
Apple_PubSub_Socket_Render = "/private/tmp/com.apple.launchd.zVE2fX6OAG/Render"
COLORFGBG = "15;0"
COLORTERM = "truecolor"
CPPFLAGS = "-I/usr/local/opt/llvm@9/include"
DISPLAY = "/private/tmp/com.apple.launchd.sPB65taKXm/org.macosforge.xquartz:0"
EDITOR = "kak"
FZF_DEFAULT_COMMAND = "rga"
FZF_DEFAULT_OPTS = ""
HOME = "/Users/abelsen"
ITERM_PROFILE = "Nord"
ITERM_SESSION_ID = "w0t0p0:9B41E652-F842-477E-B8E7-E6B79E3F94B9"
LC_CTYPE = "UTF-8"
LC_TERMINAL = "iTerm2"
LC_TERMINAL_VERSION = "3.4.3"
LDFLAGS = "-L/usr/local/opt/llvm@9/lib"
LESS = "-R"
LOGNAME = "abelsen"
LSCOLORS = "Gxfxcxdxbxegedabagacad"
MANPATH = "/usr/local/opt/erlang/lib/erlang/man:"
MONO_GAC_PREFIX = "/usr/local"
OLDPWD = "/Users/abelsen"
PAGER = "less"
PWD = "/Users/abelsen"
RBENV_SHELL = "zsh"
RUBY_CONFIGURE_OPTS = "--with-openssl-dir=/usr/local/opt/openssl@1.1"
SECURITYSESSIONID = "186a8"
SHELL = "/usr/local/bin/nu"
SHLVL = "1"
SSH_AUTH_SOCK = "/private/tmp/com.apple.launchd.xadzV7PgY5/Listeners"
TERM = "xterm-256color"
TERM_PROGRAM = "iTerm.app"
TERM_PROGRAM_VERSION = "3.4.3"
TERM_SESSION_ID = "w0t0p0:9B41E652-F842-477E-B8E7-E6B79E3F94B9"
TMPDIR = "/var/folders/4t/xzvg48wj2kj2k_vp2sc776xr0000gn/T/"
USER = "abelsen"
VIRTUALENVWRAPPER_SCRIPT = "/usr/local/bin/virtualenvwrapper.sh"
XPC_FLAGS = "0x0"
XPC_SERVICE_NAME = "0"
ZSH = "/Users/abelsen/.oh-my-zsh"
ZSH_TMUX_AUTOSTART = "true"
ZSH_TMUX_CONFIG = "/Users/abelsen/.tmux.conf"
ZSH_TMUX_TERM = "screen-256color"
_ = "/usr/local/bin/nu"
_VIRTUALENVWRAPPER_API = " mkvirtualenv rmvirtualenv lsvirtualenv showvirtualenv workon add2virtualenv cdsitepackages cdvirtualenv lssitepackages toggleglobalsitepackages cpvirtualenv setvirtualenvproject mkproject cdproject mktmpenv wipeenv allvirtualenv"
_ZSH_TMUX_FIXED_CONFIG = "/Users/abelsen/.oh-my-zsh/plugins/tmux/tmux.extra.conf"
__CF_USER_TEXT_ENCODING = "0x1F5:0x1:0xE"
